version: '3.7'

services:
  docker-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/backend/src
    env_file:
      - ./.env.docker
    ports:
      - 3000:3000

  docker-database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
